name: presentation
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  domain:
    path: ../domain
  core:
    path: ../core
  data:
    path: ../data
  freezed_annotation: ^2.4.1
  flutter_lints: ^2.0.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  flutter_svg: ^2.0.9
  transparent_image: ^2.0.1
  auto_route: ^7.8.4
  intl: ^0.18.1
  bloc_concurrency: ^0.2.2
  flutter_native_splash: ^2.3.7
  image_picker: ^1.0.5

  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  auto_route_generator: ^7.3.2
  lints: ^2.0.0
  test: ^1.21.0

flutter_intl:
  enabled: true
  arb_dir: lib/localization
  output_dir: lib/generated
