name: presentation
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  flutter_test:
    sdk: flutter
  domain:
    path: ../domain
  freezed_annotation: ^2.4.1
  flutter_lints: ^2.0.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  flutter_svg: ^2.0.9
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  lints: ^2.0.0
  test: ^1.21.0

flutter:
  assets:
    - assets/