name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  dio: ^5.3.4
  get_it: ^7.6.4
  data:
    path: ../data
  domain:
    path: ../domain
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
