name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

dependencies:
  freezed_annotation: ^2.4.1
  core:
    path: ../core

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  lints: ^2.0.0
  test: ^1.21.0
